name: Daily DressCord Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"  # 7 AM Toronto

jobs:
  send-weather-alert:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dresscord

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm start
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.https://discord.com/api/webhooks/1494457174108405960/MT6wYEtklb12clJCtTuXSASDhMQ6FVGXEaVpX_S66fSVUwwj9U0UsySV1zXUL-MwQhQ8 }}