name: Daily DressCord Alert

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"  # 7 AM Toronto
    - cron: "52 22 * * *"  # 6:50 PM Toronto

jobs:
  send-weather-alert:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dresscord

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}